django/authdj/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'authdj'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

django/djangoapp/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('authdj/', include(('authdj.urls', 'authdj'), namespace='authdj')),
    path('', include("magazine.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/templates/car.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% if car %}Редактировать{% else %}Добавить{% endif %} автомобиль</title>
</head>
<body>

<h2>{% if car %}Редактировать{% else %}Добавить{% endif %} автомобиль</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% if car %}Сохранить{% else %}Добавить{% endif %}</button>

    {% if car %}
    <button type="submit" name="delete">Удалить</button>
    {% endif %}
    <a href="{% url 'home' %}">Отмена</a>
</form>

</body>
</html>

django/templates/car_list.html
<!doctype html>
{% load is_staff %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Список машин</title>
</head>
<body>
<ul>
    {% for i in car_list %}
    <li>
        <a href="{% url 'spare_list' car_id=i.id %}">{{i.name}}</a>
        {% if request.user.is_authenticated %}
            {% if  request.user|is_staff %}
                <a href="{% url 'car_management' i.id %}">Редактировать</a>
            {% endif %}
        {% endif %}
    </li>
    {% endfor %}
</ul>
</body>
</html>

django/templates/carlist.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List car</title>
</head>
<body>
    <ul>
    {% for i in car_list %}
        <li><a href="{% url 'sparelist' car_id=i.id %}">{{i.name}}</a></li>
    {% endfor  %}
    </ul>
</body>
</html>

django/templates/completed_orders_sum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Сумма заказов</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Рассчитать</button>
</form>

{% if total_sum is not None %}
    <h2>Сумма выполненных заказов: {{ total_sum }}</h2>
{% endif %}

</body>
</html>

django/templates/home.html
<!DOCTYPE html>
{% load is_staff %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<nav>
    <ul>
        {% if request.user.is_authenticated %}
            <li>Привет, {{ request.user.username }}!</li>
            <li><a href="{% url 'authdj:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'authdj:login' %}">Войти</a></li>
            <li><a href="{% url 'authdj:register' %}">Регистрация</a></li>
        {% endif %}
    </ul>
</nav>

{% if request.user.is_authenticated %}
    {% if  request.user|is_staff %}
<p><a href="{% url 'car_add' %}">Добавить машину</a></p>
<p><a href="{% url 'spare_add' %}">Добавить деталь</a></p>
<p><a href="{% url 'order_add' %}">Добавить заказ</a></p>
<p><a href="{% url 'completed_orders_sum' %}">Расчет суммы заказов</a></p>
    {% endif %}
{% endif %}
<p><a href="{% url 'order_list' %}">Список заказов</a></p>
<p><a href="{% url 'car_list' %}">Список машин</a></p>
</body>
</html>

django/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Django</title>
</head>
<body>
    <p>Пронуза Макар Юрьевич</p>
    <p>Дата рождения: 20.01.2005</p>
    <p>Обучался в ГГТУ им. Сухого</p>
    <p>+375296574219</p>
    <img src='{% static "photo.png" %}' alt="photo">
</body>
</html>

django/templates/order.html
<!DOCTYPE html>
{% load is_staff %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if order %}Редактировать{% else %}Добавить{% endif %} заказ</title>
</head>
<body>
<h2>{% if order %}Редактировать{% else %}Добавить{% endif %}
        {% if order.is_cart %}
    корзину
        {% else %}
    заказ
        {% endif %}

</h2>

<form method="post">
    {% csrf_token %}

{% if request.user.is_authenticated %}
    {% if  request.user|is_staff %}
    {{ order_form.as_p }}

    {% endif %}
{% endif %}
    <h3>Элементы
        {% if order.is_cart %}
    корзины
        {% else %}
    заказ
        {% endif %}</h3>
    {{ order_item_formset.management_form }}
    <table>
        {% for form in order_item_formset %}
            <tr>
                <td>{{ form.as_p }}</td>
            </tr>
        {% endfor %}
    </table>

    <button type="submit">{% if order %}Сохранить{% else %}Добавить{% endif %}</button>

    {% if order %}
        <button type="submit" name="delete">Удалить</button>
    {% endif %}
    <a href="{% url 'order_list' %}">Отмена</a>
{% if request.user.is_authenticated %}
    {% if  request.user|is_staff %}
    {% if  order.id %}
    <a href="{% url 'order_approve' order_id=order.id %}">Заказать</a>
    {% endif %}

    {% endif %}
{% endif %}
</form>


</body>
</html>

django/templates/order_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список заказов</title>
</head>
<body>
<h2>Список заказов</h2>
<ul>
    {% for i in order_list %}
    <li><a href="{% url 'order_management' order_id=i.id %}">
        {% if i.is_cart %}
        Моя корзина
        {% else %}
            {{i.user}} - {{i.date}}
        {% endif %}
    </a></li>
    {% endfor %}
</ul>
</body>
</html>

django/templates/spare.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% if spare %}Редактировать{% else %}Добавить{% endif %} деталь</title>
</head>
<body>
<h2>{% if spare %}Редактировать{% else %}Добавить{% endif %} деталь</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% if spare %}Сохранить{% else %}Добавить{% endif %}</button>

    {% if spare %}
        <button type="submit" name="delete">Удалить</button>
    {% endif %}
    <a href="{% url 'home' %}">Отмена</a>
</form>

</body>
</html>

django/templates/spare_list.html
<!doctype html>
{% load is_staff %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{car.name}}</title>
</head>
<body>
    <h3>{{car_name}}</h3>
    {% for i in spare_list %}
        <p>{{i.name}}: {{i.price}} руб.
            {% if i.photo %}
    <img src="{{ i.photo.url }}" alt="{{ i.name }}">
{% else %}
    <p>Изображение отсутствует</p>
{% endif %}
        {% if request.user.is_authenticated %}
            {% if  request.user|is_staff %}
                <a href="{% url 'spare_management' i.id %}">Редактировать {{i}}</a>
            {% else %}
            <form action="{% url 'add_to_cart' i.id %}" method="get">
                <label for="count">Введите количество:</label>
                <input type="number" id="count" name="count" required min="1">
                <button type="submit">Добавить в корзину</button>
            </form>
            {% endif %}
        {% endif %}
        </p>
    {% endfor %}
</body>
</html>

django/templates/sparelist.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>list space</title>
</head>
<body>
    {% for i in spare_list %}
        <p>{{i.name}}: {{i.price}}</p>
    {% endfor  %}
</body>
</html>